# Generated by Django 4.1.4 on 2022-12-16 18:31

import cinema_app.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=16, unique=True)),
                ('street', models.CharField(max_length=32)),
                ('postal_code', models.CharField(max_length=6, validators=[cinema_app.validators.postal_code_validation])),
                ('email', models.EmailField(max_length=64)),
                ('telephone', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('\\d{9}', 'number must have 9 digits')])),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.PositiveIntegerField()),
                ('seats_columns', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(25)])),
                ('seats_rows', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(25)])),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.cinema')),
            ],
            options={
                'unique_together': {('nr', 'cinema_id')},
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('description', models.TextField(default=None)),
                ('genre', models.ManyToManyField(to='cinema_app.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.PositiveIntegerField()),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.hall')),
            ],
            options={
                'unique_together': {('nr', 'hall_id')},
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.hall')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.screening')),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.seat')),
                ('user_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('seat_id', 'screening_id')},
            },
        ),
    ]
