# Generated by Django 4.1.3 on 2022-12-05 20:10

import cinema_app.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=16, unique=True)),
                ('street', models.CharField(max_length=32)),
                ('postal_code', models.CharField(max_length=6, validators=[cinema_app.validators.postal_code_validation])),
                ('email', models.EmailField(max_length=64)),
                ('telephone', models.IntegerField(validators=[django.core.validators.RegexValidator('\\d{9}')])),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.IntegerField()),
                ('seats_columns', models.IntegerField(default=16)),
                ('seats_rows', models.IntegerField(default=12)),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('year', models.IntegerField()),
                ('description', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.IntegerField()),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration_min', models.IntegerField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('screening_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.screening')),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.seat')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('movie_id', models.ManyToManyField(to='cinema_app.movie')),
            ],
        ),
    ]
