# Generated by Django 4.1.4 on 2022-12-11 19:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='hall_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cinema_app.hall'),
            preserve_default=False,
        ),
    ]
