# Generated by Django 4.1.3 on 2022-12-05 20:17

import cinema_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0002_alter_cinema_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='telephone',
            field=models.IntegerField(validators=[cinema_app.validators.phone_num_valid]),
        ),
    ]
