# Generated by Django 4.1.4 on 2022-12-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0002_screening_hall_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
