# Generated by Django 4.1.3 on 2022-12-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0002_alter_cinema_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='seats_columns',
            field=models.IntegerField(default=16, max_length=2),
        ),
        migrations.AddField(
            model_name='hall',
            name='seats_rows',
            field=models.IntegerField(default=12, max_length=2),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='email',
            field=models.EmailField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='postal_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='telephone',
            field=models.IntegerField(max_length=9),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
    ]
