# Generated by Django 4.1.4 on 2022-12-12 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0003_alter_screening_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screening',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='screening',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
