# Generated by Django 4.1.3 on 2022-12-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0003_hall_seats_columns_hall_seats_rows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='telephone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hall',
            name='seats_columns',
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='hall',
            name='seats_rows',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(),
        ),
    ]
