# Generated by Django 4.1.3 on 2022-12-05 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0004_alter_cinema_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='telephone',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('\\d{9}')]),
        ),
    ]
