# Generated by Django 4.1.3 on 2022-12-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0004_alter_cinema_telephone_alter_hall_seats_columns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='city',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
