# Generated by Django 4.1.4 on 2022-12-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0004_rename_date_screening_start_date_screening_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='duration_min',
        ),
    ]
