# Generated by Django 4.1.3 on 2022-12-04 11:09

import cinema_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0005_alter_cinema_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='postal_code',
            field=models.CharField(max_length=6, validators=[cinema_app.models.validate_postal_code]),
        ),
    ]
