# Generated by Django 4.1.4 on 2022-12-14 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinema_app', '0005_remove_screening_duration_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='Reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('seat_id', 'screening_id')},
        ),
    ]
