# Generated by Django 4.1.3 on 2022-12-05 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0006_alter_cinema_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='seats_columns',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='hall',
            name='seats_rows',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
