# Generated by Django 4.1.3 on 2022-12-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0006_alter_cinema_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='postal_code',
            field=models.CharField(max_length=6),
        ),
    ]
