# Generated by Django 4.1.3 on 2022-12-05 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0007_alter_hall_seats_columns_alter_hall_seats_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='seats_columns',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='hall',
            name='seats_rows',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='screening',
            name='duration_min',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='nr',
            field=models.PositiveIntegerField(),
        ),
    ]
