# Generated by Django 4.1.4 on 2022-12-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0007_alter_reservation_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(default='x', max_length=8),
            preserve_default=False,
        ),
    ]
