# Generated by Django 4.1.3 on 2022-12-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0008_alter_hall_seats_columns_alter_hall_seats_rows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='nr',
            field=models.PositiveIntegerField(),
        ),
    ]
