# Generated by Django 4.1.3 on 2022-12-05 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0009_alter_hall_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='seats_columns',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='hall',
            name='seats_rows',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
