# Generated by Django 4.1.4 on 2022-12-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0009_delete_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='available',
        ),
    ]
