# Generated by Django 4.1.3 on 2022-12-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0011_alter_hall_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('nr', 'hall_id')},
        ),
    ]
