# Generated by Django 4.1.4 on 2022-12-10 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0012_alter_seat_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='seats_columns',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='hall',
            name='seats_rows',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
