# Generated by Django 4.1.4 on 2022-12-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0014_alter_movie_year_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='cinema_app.genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
